services:
  ppe-viewer:
    build: .
    container_name: ppe-video-viewer
    ports:
      - "3000:3000"
    volumes:
      # Mount uploads directory for persistent storage
      - ./uploads:/app/uploads
      # Mount temp directory for temporary files
      - ./temp:/app/temp
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ppe-network

networks:
  ppe-network:
    driver: bridge 